apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: test
  labels:
    app: api-projects
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 80      # this can be change right here
      targetPort: 3001  # it has match with program 